name: "MasnyLib"
version: ${pluginVersion}
main: dev.masnypen.masnyLib.MasnyLib
api-version: '${pluginAPI}'
authors: [MasnyPen]
website: masnypen.dev
load: STARTUP

permissions:
  serweronlib.admin:
    default: op
